### PR TITLE
add protocol as parsed from url to opts, fixes #51

### LINKED ISSUE #51: protocol specified in url is not passed to underlying http/https module
This is a problem in the following scenario:

The code

    require('hyperquest')('https://foo.com/bar')

is being browserified and served from an *http* url.

Since hyperquest does not set `opts.protocol`, the underlying module `stream-http` will infer it from `navigator.location`, which results in the wrong url being fetched, namely `http://foo.com:443/bar`.

### PR DESCRIPTION
**Pull request by regular**
fixes http request made by a page that was loaded from an http url (see #51 51)

### CODE REVIEW

**Comment by juliangruber** [comment]
would you mind adding a test for this, so it won't be un-fixed by accident in the future?

**Comment by regular** [comment]
You don't currently seem to test in a browser environment at all, right?
Since the test requires a browser, I would go ahead and add browserify and testling as dev dependencies and run the test through testling.

Does that sound good?

**Comment by juliangruber** [comment]
hmm, if this doesn't need to be fixed in node envs, there's a discrepancy between node core and browserify's version of node core and I'd say that's what should be fixed.

**Comment by regular** [comment]
Come to think of it, you are right.

Using the `https` module for https:// requests should be enough to ensure that the protocol being used actually is https (that's what hyperquest does). It is the fact that `browserify-https` forwards everything to `stream-http` and `stream-http` ignoring the `scheme` option and instead inferring it from `navigator.location` that causes the problem.

Well, thanks for helping to figure that out anyway :)

**Pull request closed without merging**
